- hosts: localhost
  vars:

  tasks:
  - name: install basee
    yum:
      name: firefox
      state: latest

    yum:
      name: plasma
      state: latest

    yum:
      name: discord
      state: latest

  - name: write the apache config file
    template:
      src: /srv/httpd.j2
      dest: /etc/httpd.conf
    notify:
    - restart apache
  - name: ensure apache is running
    service:
      name: httpd
      state: started
  handlers:
    - name: restart apache
      service:
        name: httpd
        state: restarted